name: Publish Kitodo.Production ActiveMQ

on:
  push:
    branches: 
      - main
  workflow_dispatch: # run manually

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kitodo.Production ActiveMQ Repository
        uses: actions/checkout@v3

      - # Activate cache export feature to reduce build time of images
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine build args
        run: |
          date -u +"build_date=%Y-%m-%dT%H:%M:%SZ" >> $GITHUB_ENV
          echo "vcs_ref=`git -C ./ rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Build the Kitodo.Production ActiveMQ image and deploy to GitHub Container Repository
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            BUILD_DATE=${{ env.build_date }}
            VCS_REF=${{ env.vcs_ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
